[package]
name = "life-game"
version = "0.1.0"
edition = "2024"

[dependencies]
fixedbitset = "0.5.7"
js-sys = "0.3.77"
wasm-bindgen = "0.2.100"

[dependencies.web-sys]
version = "0.3.77"
features = [
	"console",
]

[lib]
crate-type = ["cdylib", "rlib"]
